;;;; json.lisp -- minimal JSON codec.
;;;;
;;;; Lisp representation:
;;;;   object  -> (:obj ("key" . value) ...)      build with (obj "k" v ...)
;;;;   array   -> list (NIL is the empty array) or non-string vector
;;;;   string  -> string
;;;;   number  -> integer / real
;;;;   true / false / null -> :true / :false / :null

(in-package :symchess)

(defun obj (&rest kvs)
  (cons :obj (loop for (k v) on kvs by #'cddr collect (cons k v))))

(defun objp (x)
  (and (consp x) (eq (car x) :obj)))

(defun jget (o key &optional default)
  (if (objp o)
      (let ((cell (assoc key (cdr o) :test #'string=)))
        (if cell (cdr cell) default))
      default))

(defun jset (o key value)
  "Destructively set KEY in object O; returns O."
  (let ((cell (assoc key (cdr o) :test #'string=)))
    (if cell
        (setf (cdr cell) value)
        (setf (cdr o) (append (cdr o) (list (cons key value)))))
    o))

(defun jbool (x) (if x :true :false))

(defun jnull (x) (if x x :null))

(defun write-json-string (str out)
  (write-char #\" out)
  (loop for ch across str
        for code = (char-code ch)
        do (cond ((char= ch #\") (write-string "\\\"" out))
                 ((char= ch #\\) (write-string "\\\\" out))
                 ((= code 10) (write-string "\\n" out))
                 ((= code 13) (write-string "\\r" out))
                 ((= code 9) (write-string "\\t" out))
                 ((< code 32) (format out "\\u~4,'0X" code))
                 (t (write-char ch out))))
  (write-char #\" out))

(defun write-json (x out)
  (cond ((eq x :true) (write-string "true" out))
        ((eq x :false) (write-string "false" out))
        ((eq x :null) (write-string "null" out))
        ((stringp x) (write-json-string x out))
        ((integerp x) (format out "~D" x))
        ((realp x) (format out "~,3F" x))
        ((objp x)
         (write-char #\{ out)
         (loop for (k . v) in (cdr x)
               for first = t then nil
               do (unless first (write-char #\, out))
                  (write-json-string k out)
                  (write-char #\: out)
                  (write-json v out))
         (write-char #\} out))
        ((listp x)
         (write-char #\[ out)
         (loop for v in x
               for first = t then nil
               do (unless first (write-char #\, out))
                  (write-json v out))
         (write-char #\] out))
        ((vectorp x) (write-json (coerce x 'list) out))
        ((keywordp x) (write-json-string (string-downcase (symbol-name x)) out))
        (t (error "Cannot encode ~S as JSON" x))))

(defun json-encode (x)
  (with-output-to-string (out) (write-json x out)))

;;; ---------------------------------------------------------------- decoding

(defun json-decode (string)
  (let ((i 0) (n (length string)))
    (labels ((peek () (if (< i n) (char string i) (error "Unexpected end of JSON")))
             (skip-ws ()
               (loop while (and (< i n)
                                (member (char string i) '(#\Space #\Tab #\Newline #\Return)))
                     do (incf i)))
             (expect (ch)
               (unless (char= (peek) ch)
                 (error "JSON: expected ~C at ~D, found ~C" ch i (peek)))
               (incf i))
             (literal (text value)
               (let ((end (+ i (length text))))
                 (unless (and (<= end n) (string= text string :start2 i :end2 end))
                   (error "JSON: bad literal at ~D" i))
                 (setf i end)
                 value))
             (parse-string ()
               (expect #\")
               (with-output-to-string (out)
                 (loop
                   (let ((ch (peek)))
                     (incf i)
                     (cond ((char= ch #\") (return))
                           ((char= ch #\\)
                            (let ((esc (peek)))
                              (incf i)
                              (case esc
                                (#\n (write-char #\Newline out))
                                (#\r (write-char #\Return out))
                                (#\t (write-char #\Tab out))
                                (#\b (write-char #\Backspace out))
                                (#\f (write-char #\Page out))
                                (#\u (write-char
                                      (code-char (parse-integer string :start i :end (+ i 4)
                                                                       :radix 16))
                                      out)
                                 (incf i 4))
                                (t (write-char esc out)))))
                           (t (write-char ch out)))))))
             (parse-number ()
               (let ((start i))
                 (loop while (and (< i n) (find (char string i) "+-0123456789.eE"))
                       do (incf i))
                 (let ((text (subseq string start i)))
                   (if (find-if (lambda (c) (find c ".eE")) text)
                       (let ((*read-default-float-format* 'double-float)
                             (*read-eval* nil))
                         (let ((v (read-from-string text)))
                           (unless (realp v) (error "JSON: bad number ~A" text))
                           v))
                       (parse-integer text)))))
             (parse-value ()
               (skip-ws)
               (let ((ch (peek)))
                 (cond ((char= ch #\{)
                        (incf i)
                        (skip-ws)
                        (if (char= (peek) #\})
                            (progn (incf i) (list :obj))
                            (let ((pairs '()))
                              (loop
                                (skip-ws)
                                (let ((k (parse-string)))
                                  (skip-ws)
                                  (expect #\:)
                                  (push (cons k (parse-value)) pairs))
                                (skip-ws)
                                (if (char= (peek) #\,)
                                    (incf i)
                                    (progn (expect #\}) (return))))
                              (cons :obj (nreverse pairs)))))
                       ((char= ch #\[)
                        (incf i)
                        (skip-ws)
                        (if (char= (peek) #\])
                            (progn (incf i) '())
                            (let ((items '()))
                              (loop
                                (push (parse-value) items)
                                (skip-ws)
                                (if (char= (peek) #\,)
                                    (incf i)
                                    (progn (expect #\]) (return))))
                              (nreverse items))))
                       ((char= ch #\") (parse-string))
                       ((char= ch #\t) (literal "true" :true))
                       ((char= ch #\f) (literal "false" :false))
                       ((char= ch #\n) (literal "null" :null))
                       (t (parse-number))))))
      (prog1 (parse-value)
        (skip-ws)
        (when (< i n) (error "JSON: trailing characters at ~D" i))))))
