;;;; movegen.lisp -- pseudo-legal move generation, legality filter, perft.

(in-package :symchess)

(deftype move-array () '(simple-array fixnum (256)))

(defun make-move-array ()
  (make-array 256 :element-type 'fixnum :initial-element 0))

(defun generate-moves (p moves &optional captures-only)
  "Fill MOVES with pseudo-legal moves for the side to move and return how many.
With CAPTURES-ONLY, generate only captures and promotions (for quiescence)."
  (declare (type pos p) (type move-array moves))
  (let* ((b (pos-board p))
         (side (pos-side p))
         (n 0)
         (fwd (* 16 side))
         (start-rank (if (= side 1) 1 6))
         (promo-rank (if (= side 1) 7 0))
         (ep (pos-ep p)))
    (declare (type fixnum n))
    (flet ((add (m) (setf (aref moves n) m) (incf n)))
      (declare (inline add))
      (dotimes (sq 128)
        (when (on-board-p sq)
          (let ((piece (aref b sq)))
            (when (and (/= piece 0) (= (signum piece) side))
              (let ((kind (abs piece)))
                (cond
                  ;; ---- pawns
                  ((= kind +pawn+)
                   (let ((to (+ sq fwd)))
                     (when (zerop (aref b to))
                       (cond ((= (sq-rank to) promo-rank)
                              (loop for promo from +queen+ downto +knight+
                                    do (add (make-move-code sq to :promo promo))))
                             ((not captures-only)
                              (add (make-move-code sq to))
                              (when (and (= (sq-rank sq) start-rank)
                                         (zerop (aref b (+ to fwd))))
                                (add (make-move-code sq (+ to fwd) :double t)))))))
                   (dolist (d '(15 17))
                     (let ((to (+ sq (* side d))))
                       (when (on-board-p to)
                         (let ((target (aref b to)))
                           (cond ((and (/= target 0) (/= (signum target) side))
                                  (if (= (sq-rank to) promo-rank)
                                      (loop for promo from +queen+ downto +knight+
                                            do (add (make-move-code sq to :promo promo
                                                                          :capture t)))
                                      (add (make-move-code sq to :capture t))))
                                 ((= to ep)
                                  (add (make-move-code sq to :capture t :ep t)))))))))
                  ;; ---- knights and kings
                  ((or (= kind +knight+) (= kind +king+))
                   (let ((offsets (if (= kind +knight+) **knight-offsets** **king-offsets**)))
                     (dotimes (i 8)
                       (let ((to (+ sq (aref offsets i))))
                         (when (and (>= to 0) (on-board-p to))
                           (let ((target (aref b to)))
                             (cond ((zerop target)
                                    (unless captures-only (add (make-move-code sq to))))
                                   ((/= (signum target) side)
                                    (add (make-move-code sq to :capture t)))))))))
                   (when (and (= kind +king+) (not captures-only))
                     (let ((rights (pos-castling p)) (enemy (- side)))
                       (if (= side 1)
                           (when (= sq 4)
                             (when (and (logtest rights 1)
                                        (zerop (aref b 5)) (zerop (aref b 6))
                                        (= (aref b 7) +rook+)
                                        (not (square-attacked-p p 4 enemy))
                                        (not (square-attacked-p p 5 enemy)))
                               (add (make-move-code 4 6 :castle t)))
                             (when (and (logtest rights 2)
                                        (zerop (aref b 3)) (zerop (aref b 2)) (zerop (aref b 1))
                                        (= (aref b 0) +rook+)
                                        (not (square-attacked-p p 4 enemy))
                                        (not (square-attacked-p p 3 enemy)))
                               (add (make-move-code 4 2 :castle t))))
                           (when (= sq 116)
                             (when (and (logtest rights 4)
                                        (zerop (aref b 117)) (zerop (aref b 118))
                                        (= (aref b 119) (- +rook+))
                                        (not (square-attacked-p p 116 enemy))
                                        (not (square-attacked-p p 117 enemy)))
                               (add (make-move-code 116 118 :castle t)))
                             (when (and (logtest rights 8)
                                        (zerop (aref b 115)) (zerop (aref b 114))
                                        (zerop (aref b 113))
                                        (= (aref b 112) (- +rook+))
                                        (not (square-attacked-p p 116 enemy))
                                        (not (square-attacked-p p 115 enemy)))
                               (add (make-move-code 116 114 :castle t))))))))
                  ;; ---- sliders
                  (t
                   (flet ((slide (offsets)
                            (declare (type (simple-array fixnum (*)) offsets))
                            (dotimes (i 4)
                              (let ((d (aref offsets i)))
                                (loop for to = (+ sq d) then (+ to d)
                                      while (and (>= to 0) (on-board-p to))
                                      do (let ((target (aref b to)))
                                           (cond ((zerop target)
                                                  (unless captures-only
                                                    (add (make-move-code sq to))))
                                                 (t
                                                  (when (/= (signum target) side)
                                                    (add (make-move-code sq to :capture t)))
                                                  (return)))))))))
                     (when (or (= kind +bishop+) (= kind +queen+)) (slide **bishop-offsets**))
                     (when (or (= kind +rook+) (= kind +queen+)) (slide **rook-offsets**)))))))))))
    n))

(defun legal-moves (p)
  "List of legal moves in generation order."
  (let* ((moves (make-move-array))
         (n (generate-moves p moves))
         (legal '()))
    (dotimes (i n)
      (let ((m (aref moves i)))
        (when (make-move p m)
          (unmake-move p)
          (push m legal))))
    (nreverse legal)))

(defun has-legal-move-p (p)
  (let* ((moves (make-move-array))
         (n (generate-moves p moves)))
    (dotimes (i n nil)
      (when (make-move p (aref moves i))
        (unmake-move p)
        (return t)))))

(defun perft (p depth)
  "Count leaf nodes of the legal move tree: the standard movegen correctness test."
  (if (zerop depth)
      1
      (let* ((moves (make-move-array))
             (n (generate-moves p moves))
             (total 0))
        (dotimes (i n total)
          (when (make-move p (aref moves i))
            (incf total (perft p (1- depth)))
            (unmake-move p))))))

(defun insufficient-material-p (p)
  "K vs K, or K+minor vs K."
  (let ((minors 0) (b (pos-board p)))
    (dotimes (sq 128 (<= minors 1))
      (when (on-board-p sq)
        (let ((kind (abs (aref b sq))))
          (cond ((or (= kind +pawn+) (= kind +rook+) (= kind +queen+)) (return nil))
                ((or (= kind +knight+) (= kind +bishop+)) (incf minors))))))))
